language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt install jq
  - sudo apt install libxml2-utils
  
script:
  - echo "Script started..."
  # Validate sample documents using Travis CI
  - ./validate.sh
